### PR TITLE
enhanced style

### PR DESCRIPTION
**Pull request by codernotme**
Screenshot 2024-10-20 221558
Screenshot 2024-10-20 221643
enhanced Home page and video page

### CODE REVIEW

**Comment by Shobhit2205** [comment]
@codernotme UI looks great, but can you make it more responsive for mobile?

**Comment by codernotme** [comment]
> @codernotme UI looks great, but can you make it more responsive for mobile?

Yeah sure I will try to improvise it more...

Would you happen to have any more suggestions?

And would you please merge this so that I also get some credits on hackobter

**Comment by codernotme** [comment]
In addition to this, I would like to give a PR for `README.md` a more enhanced and visually appealing look. If you want, I can push that, too.

**Comment by Shobhit2205** [comment]
just make home page responsive for mobile and in chat page the screen should not shrink

**Comment by codernotme** [comment]
> just make home page responsive for mobile and in chat page the screen should not shrink

alright

**Comment by codernotme** [comment]
Updated Ui

Screenshot 2024-10-21 124003

Screenshot 2024-10-21 123939
Screenshot 2024-10-21 123946
Screenshot 2024-10-21 123957

Screenshot 2024-10-21 123933

**Comment by Shobhit2205** [comment]
merged PR

**Pull request merged**
